### ISSUE TITLE
Missing MessageCenter get_views classes [resolved]

### ISSUE THREAD

**Issue by RetSamys** [danopia/deviantart-difi#2]
Wonderful wiki! Thank you for all the hard work. Allow me to mention this one new class that I've discovered:
`oq:fb_mentions:0:0:f`

I'm not giving up on finding something to show me the Groups notification in the splintered menu as opposed to calling each individual Group as a separate folder. I'll let you know as soon as I find out more - unless I'm stupid enough to have missed it in your wiki.

**Comment by DRSDavidSoft** [comment]
Nice work. We need more people to analyze DiFi and document it as much as possible.
I added the account mentions on diff #2334e48 ([link](https://github.com/danopia/deviantart-difi/wiki/MessageCenter/_compare/4db1b06b05f25915ed8fa31e3bc1530508962e88...2334e489ee62e44e7a46e734ed2f8be24cf49846)).

**Comment by danopia** [comment]
Hey @RetSamys, by recommendation of @DRSDavidSoft I've invited you as a collaborator. If you accept the invite you'll be able to edit the wiki directly. Thank you for your contributions 😄
