### ISSUE TITLE
Found another one!

### ISSUE THREAD

**Issue by RetSamys** [danopia/deviantart-difi#3]
`oq:devwatch:0:48:f:tg=groupdeviations`
This also is a newer part of the Notifications: The Group Deviations.
And here I was excited that it was the Group admin notification... still not giving up.

**Comment by DRSDavidSoft** [comment]
[Fixed](https://github.com/danopia/deviantart-difi/wiki/MessageCenter/_compare/2334e489ee62e44e7a46e734ed2f8be24cf49846...5da94f2e6fd39511088e05a714bc34ad97df6791). I'll see if I can give you write access to this Wiki, so you can continue documenting it, directly. In the meantime keep up the good work.

P.S., Group admin notifications don't work that way. They are regular notifications just grouped in a different folder, so you first have to scrape out the Group folder ID, and request messages and notifications in that folder respectively.

What are you trying to achieve? What is your programming language? Note me on dA, maybe I can help you with it. I've written a code specifically for parsing Notification Center messages for my [dADroid](http://dADroid.ir) bot.
